name: Deploy Genea

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          genea-app/client/package-lock.json
          genea-app/server/package-lock.json
    
    - name: Install client dependencies
      run: |
        cd genea-app/client
        npm ci
    
    - name: Install server dependencies
      run: |
        cd genea-app/server
        npm ci
    
    - name: Build client
      run: |
        cd genea-app/client
        npm run build
    
    - name: Run server tests
      run: |
        cd genea-app/server
        npm test